### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [Nightenndy/homework-kinozal#1]
1)
внешний вид блока не соответствует мастер-шаблону
![image](https://user-images.githubusercontent.com/8464662/77318875-7e116a00-6d16-11ea-9900-32f4e367be77.png)

2)
нет скруглений
![image](https://user-images.githubusercontent.com/8464662/77318934-9b463880-6d16-11ea-8c3e-a56c88063751.png)

3)
отступы
![image](https://user-images.githubusercontent.com/8464662/77319174-0728a100-6d17-11ea-8fe1-bb0a666548b1.png)

4)
обрыв блока
![image](https://user-images.githubusercontent.com/8464662/77319206-127bcc80-6d17-11ea-9a3e-03f6498390ed.png)

5)
шрифт
![image](https://user-images.githubusercontent.com/8464662/77319287-39d29980-6d17-11ea-943b-03a9bb81b3ba.png)

6)
крах сетки
![image](https://user-images.githubusercontent.com/8464662/77319302-46ef8880-6d17-11ea-9262-32effbb3b06f.png)

7)
невалидный код
![image](https://user-images.githubusercontent.com/8464662/77319347-5ff83980-6d17-11ea-8fd9-dea728c31329.png)

**Comment by Alecto** [comment]
4 - не исправлено

**Comment by Alecto** [comment]
8)
добавьте отступы между группами
![image](https://user-images.githubusercontent.com/8464662/77886773-1d33e580-7272-11ea-96e2-e618e359dd81.png)

**Comment by Nightenndy** [comment]
Ошибку исправил!)

March 30, 2020 at 12:36 AM Andrey <notifications@github.com> написал(а):






добавьте отступы между группами

**Comment by Alecto** [comment]
2 ссылки пожалуйста.

ср, 1 квіт. 2020 о 13:32 Anton Kharlamov <notifications@github.com> пише:

**Comment by Nightenndy** [comment]
Извиняюсь, совсем забыл про ссылки( 


https://github.com/Nightenndy/homework-kinozal


https://nightenndy.github.io/homework-kinozal/

April 1, 2020 at 6:35 AM Andrey <notifications@github.com> написал(а):






2 ссылки пожалуйста.

ср, 1 квіт. 2020 о 13:32 Anton Kharlamov <notifications@github.com> пише:

**Comment by Alecto** [comment]
правильно.
работа принята.

ср, 1 квіт. 2020 о 18:29 Anton Kharlamov <notifications@github.com> пише:
